name: cfd_optimisation_env
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - ca-certificates=2021.10.8=h033912b_0
  - cffi=1.15.0=py37h446072c_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - distlib=0.3.4=pyhd8ed1ab_0
  - filelock=3.6.0=pyhd8ed1ab_0
  - identify=2.5.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.3=py37hf985489_1
  - importlib_metadata=4.11.3=hd8ed1ab_1
  - libcxx=13.0.1=hc203e6f_0
  - libffi=3.4.2=h0d85af4_5
  - libzlib=1.2.11=h6c3fc93_1014
  - ncurses=6.3=h96cf925_1
  - nodeenv=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.3=hfe4f2af_0
  - pip=22.0.4=pyhd8ed1ab_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - pre-commit=2.18.1=py37hf985489_1
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.7.12=hf3644f1_100_cpython
  - python_abi=3.7=2_cp37m
  - pyyaml=6.0=py37h69ee0a8_4
  - readline=8.1=h05e3726_0
  - setuptools=62.1.0=py37hf985489_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.3=hd9f0692_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - typing_extensions=4.2.0=pyha770c72_1
  - ukkonen=1.0.1=py37h18621fa_2
  - virtualenv=20.14.1=py37hf985489_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=h0d85af4_2
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h6c3fc93_1014
  - pip:
    - git+https://github.com/trsav/bayes_opt_with_constraints@master
    - black==22.3.0
    - click==8.1.3
    - cycler==0.11.0
    - fonttools==4.33.3
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.2
    - mypy-extensions==0.4.3
    - numpy==1.21.6
    - packaging==21.3
    - pathspec==0.9.0
    - pillow==9.1.0
    - pyfoam==2021.6
    - pyparsing==3.0.8
    - python-dateutil==2.8.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - typed-ast==1.5.3
prefix: /opt/miniconda3/envs/cfd_optimisation_env
