name: cfd_optimisation_env
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - black=22.3.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - click=8.1.3
  - cycler=0.11.0
  - dataclasses=0.8
  - fonttools=4.33.3
  - freetype=2.10.4
  - giflib=5.2.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.3
  - libdeflate=1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=14.0.3
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=3.0.3
  - packaging=21.3
  - pandas=1.4.2
  - pathspec=0.9.0
  - pillow=9.1.1
  - pip=22.1.1
  - platformdirs=2.5.1
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - readline=8.1
  - setuptools=62.3.2
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.1
  - typed-ast=1.5.4
  - typing_extensions=4.2.0
  - tzdata=2022a
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - absl-py=
    - attrs=
    - cfgv=
    - chex=
    - cloudpickle=
    - contextlib2=
    - decorator=
    - deprecation=
    - distlib=
    - distrax=
    - dm-tree=
    - filelock=
    - flatbuffers=
    - gast=
    - gpjax=
    - identify=
    - iniconfig=
    - jax=
    - jaxkern=
    - jaxlib=
    - jaxlinop=
    - jaxtyping=
    - jaxutils=
    - jinja2=
    - markupsafe=
    - ml-collections=
    - nodeenv=
    - opt-einsum=
    - optax=
    - pluggy=
    - pre-commit=
    - py=
    - pyfoam=
    - pytest=
    - pyyaml=
    - scipy=
    - tensorflow-probability=
    - toml=
    - toolz=
    - tqdm=
    - typeguard=
    - virtualenv=
