name: pulsed-reactor-optimisation_env
channels:
  - defaults
dependencies:
  - appdirs=1.4.4=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py39he3068b8_1
  - brotli=1.0.9=hb1e8313_2
  - ca-certificates=2021.7.5=hecd8cb5_1
  - certifi=2021.5.30=py39hecd8cb5_0
  - click=8.0.1=pyhd3eb1b0_0
  - cycler=0.10.0=py39hecd8cb5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=ha233b18_0
  - importlib-metadata=3.10.0=py39hecd8cb5_0
  - intel-openmp=2021.3.0=hecd8cb5_3375
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.3.1=py39h23ab428_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.2.0=h87d7836_0
  - libwebp-base=1.2.0=h9ed2024_0
  - lz4-c=1.9.3=h23ab428_1
  - matplotlib=3.4.2=py39hecd8cb5_0
  - matplotlib-base=3.4.2=py39h8b3ea08_0
  - mkl=2021.3.0=hecd8cb5_517
  - mkl-service=2.4.0=py39h9ed2024_0
  - mkl_fft=1.3.0=py39h4a7008c_2
  - mkl_random=1.2.2=py39hb2f4e1b_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39hecd8cb5_0
  - ncurses=6.2=h0a44026_1
  - numexpr=2.7.3=py39h5873af2_1
  - numpy=1.20.3=py39h4b4dc7a_0
  - numpy-base=1.20.3=py39he0bd621_0
  - olefile=0.46=py_0
  - openjpeg=2.4.0=h66ea3da_0
  - openssl=1.1.1l=h9ed2024_0
  - pandas=1.3.2=py39h5008ddb_0
  - pathspec=0.7.0=py_0
  - pillow=8.3.1=py39ha4cf6ea_0
  - pip=21.2.4=py37hecd8cb5_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - python=3.9.6=h88f2d9e_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - regex=2021.8.3=py39h9ed2024_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py39h9ed2024_0
  - typed-ast=1.4.3=py39h9ed2024_1
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - absl-py==0.13.0
    - backports-entry-points-selectable==1.1.0
    - bayesian-optimization==1.2.0
    - cfgv==3.3.1
    - distlib==0.3.2
    - filelock==3.0.12
    - flatbuffers==2.0
    - identify==2.2.13
    - iniconfig==1.1.1
    - jax==0.2.20
    - jaxlib==0.1.71
    - joblib==1.0.1
    - nodeenv==1.6.0
    - opt-einsum==3.3.0
    - packaging==21.0
    - platformdirs==2.3.0
    - pluggy==1.0.0
    - pre-commit==2.15.0
    - py==1.10.0
    - pytest==6.2.5
    - pyyaml==5.4.1
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - threadpoolctl==2.2.0
    - virtualenv==20.7.2
prefix: /opt/miniconda3/envs/pulsed-reactor-optimisation_env
