name: mf_design_env
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - python=3.10.4
  - pip:
    - gpjax
    - jax
    - jaxkern
    - jaxlib
    - jaxlinop
    - jaxtyping
    - jaxutils
    - jinja2
    - markupsafe
    - ml-collections
    - matplotlib
    - numpy
    - imageio
    - optax
    - pre-commit
    - py
    - pyfoam
    - pytest
    - pyyaml
    - scipy
    - toml
    - toolz
    - tqdm
    - typeguard
    - virtualenv
